# Generated by Django 3.1.6 on 2021-04-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre Completo'),
        ),
    ]
